### ISSUE TITLE
Cannot find nuget package

### ISSUE THREAD

**Issue by ignatandrei** [atifaziz/Transplator#3]
I want to make a simple tutorial for this application ( available at https://github.com/ignatandrei/RSCG_Examples )
I cannot find the nuget package

https://www.nuget.org/packages?q=transplator

**Comment by atifaziz** [comment]
I have not published a package because I am unsure about the overall design (feature- and otherwise) and therefore not ready to commit to the project yet. Once I publish, I usually stand behind my projects for years. The idea of publishing it on GitHub was to gather feedback and ideas. I might decide to publish an alpha version or a "0.1" at some point just to indicate that the project is in its incubation period.

**Comment by ignatandrei** [comment]
0.1 it is perfect. Please do!

**Comment by atifaziz** [comment]
Sure, but I cannot commit on when. Meanwhile and while painful, people can build and reference the package locally if it's just for a tutorial.

**Comment by atifaziz** [comment]
Of course a PR to help with this would be welcome. 😉

**Comment by ignatandrei** [comment]
Ok

**Comment by ignatandrei** [comment]
Just put those in .csproj

 <PropertyGroup>
<Description>       </Description>
    <Version></Version>
    <Authors></Authors>
    <PackageTags>RoslynCodeGenerators;C#;CSharp;</PackageTags>
    <PackageProjectUrl>https://github.com/atifaziz/Transplator<PackageProjectUrl>
    <RepositoryUrl>https://github.com/atifaziz/Transplator</RepositoryUrl>
    <RepositoryType>GIT</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>MIT</Copyright>

 </PropertyGroup>

and use 
dotnet pack

**Comment by atifaziz** [comment]
Looking at “[Package a generator as a NuGet package](https://github.com/dotnet/roslyn/blob/0148ce43aeda7c4720c51c06b90750a1005c053b/docs/features/source-generators.cookbook.md#package-a-generator-as-a-nuget-package)”, I don't think it's that simple? Although it's not _that_ complicated either.

**Comment by ignatandrei** [comment]
Something new ?

**Comment by atifaziz** [comment]
[CI packages are now being published](https://www.myget.org/feed/raboof/package/nuget/Transplator).

You can add a `NuGet.config` file to your project via `dotnet new nugetconfig` and configure the feed in there as follows:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="raboof@myget.org" value="https://www.myget.org/F/raboof/api/v3/index.json" />
  </packageSources>
</configuration>
```

@ignatandrei Would be great if you can take it for a spin and confirm that it works well on your end. I've also uploaded [`sample.zip`](https://github.com/atifaziz/Transplator/files/6610192/sample.zip) with the feed configured. You should be able to unzip on your end and just execute `dotnet run` with the unzipped location as the current working directory. You will need [.NET SDK 5.0.300 or a later version](https://dotnet.microsoft.com/download/dotnet/5.0). I tried in a Docker image with the following command line:

    docker run --rm mcr.microsoft.com/dotnet/sdk:5.0 /bin/sh -c 'apt-get update -y && apt-get install -y unzip && mkdir eg && cd eg && curl -OL https://github.com/atifaziz/Transplator/files/6610192/sample.zip && unzip sample.zip && dotnet run --verbosity normal'

and it worked smoothly so I am guessing it should work for you too. Nevertheless, if you can help confirm then I'll proceed to publish the package also on [nuget.org](https://www.nuget.org/).

**Comment by ignatandrei** [comment]
Great . I will verify ASAP

**Comment by ignatandrei** [comment]
It works with docker ( I have put one command after another , the whole command did not work ).
PLease publish on NuGet. I will make a review on my RSCG examples, https://github.com/ignatandrei/RSCG_Examples

**Comment by atifaziz** [comment]
[Version 0.2.0 is published](https://github.com/atifaziz/Transplator/releases/tag/v0.2.0). Looking forward to your tutorial.

**Comment by ignatandrei** [comment]
https://github.com/ignatandrei/RSCG_Examples/tree/main/TemplateRender
You have also email - please answer
